name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '22.20.0'
            cache: 'npm'

        - name: Instalar dependências
          run: npm ci
          working-directory: ./bootcamp-chrome-extension       

        - name: Instalar Playwright (Chromium + deps)
          run: npx playwright install --with-deps chromium
          working-directory: ./bootcamp-chrome-extension

        - name: Build extensão
          run: npm run build
          working-directory: ./bootcamp-chrome-extension

        - name: Teste e2e
          run: xvfb-run -a npm run test:e2e
          working-directory: ./bootcamp-chrome-extension

        - name: Publicar o retatório HTML do teste
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: playwright-report
            path: bootcamp-chrome-extension/playwright-report

        - name: Publicar o pacote de extensão (ZIP)
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: extension-zip
            path: bootcamp-chrome-extension/dist/extension.zip


